### ISSUE TITLE
Component selection broken after scroll

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#312]
The correct component is not selected in some cases, when the prosemirror editor is active.

### Reproduce
- Set up a site with height greater than viewport height (so it can be scrolled)
- Create a text component and edit text (prosemirror editor opened)
- Scroll down the page
- Attempt to select a component
- See bug (the view scrolls back up to the prosemirror editor, and the new component is not selected)

https://github.com/samatechtw/pubstudio-builder/assets/550982/eb73ff1a-fc1d-4606-8e98-9c77a06b81c2

**Comment by abemscac** [comment]
Hi @sampullman 

It looks like the issue is caused by the dispatch of `const tr = view.state.tr.setMeta('selDeco', {})` in `pubstudio-builder/libs/frontend/feature-render-builder/src/components/ProseMirrorEditor.ts:171`.
The `selDeco` metadata is used to add a `sel` class to the selected portion in the editor, but the editor seems to behave the same without the `selPlugin`; I think I must've missed something. Is this `sel` class the same thing as the one defined in `pubstudio-builder/libs/frontend/ui-theme/src/css/components/prosemirror-view.postcss:5`? 🤔

**Comment by sampullman** [comment]
Good question, I can't remember adding `'selDeco'` here. The purpose is not obvious at first glance, I should have included a comment!

If I had to guess, I'd say it's related to retaining the selected component when the style toolbar is clicked, so we can apply a style to the correct selection. But if it's removed and that or anything else related to the editor doesn't break, it should be fine.
