### ISSUE TITLE
Disable backups when S3 env is not present

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#6]
Disable automated site backups when S3 env vars are not provided.

### Tasks
- When `S3_URL`, `S3_ACCESS_KEY_ID`, or `S3_SECRET_ACCESS_KEY` are not provided, don't trigger automatic backups
- Backup related endpoint should return error `404`
- Print a warning on startup if backups are disabled

**Comment by ClaireMao1996** [comment]
Base on the call, we are not providing `S3_SECRET_ACCESS_KEY` in `platform-api.k8s-config.yaml` and `site-api1.k8s-config.yaml`, so if we add this check during CI/DEV, the tests for backups will always return 404.

Based on the conclusion,
1. `list_backups` won't perform this check because it doesn't involve S3.
2. Bypass CI and DEV because the tests will fail (Add comments in the code to explain this situation)

**Comment by ClaireMao1996** [comment]
Or, would you prefer if we add `S3_SECRET_ACCESS_KEY: dev` to yaml? This way, we won't need to perform additional environment checks.

**Comment by sampullman** [comment]
Yeah! If that makes everything work as expected I think it's a good idea.
